# Generated by Django 4.1.1 on 2022-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='weburl',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
